/**
 * Real Bright House photographs. Originals live in src/assets/photos and are
 * never modified; Astro generates optimized AVIF/WebP versions at build time.
 * Privacy-safe crops (photos 03 and 08) are generated by scripts/make-crops.mjs.
 *
 * To add or swap a photo: drop the file into src/assets/photos, import it
 * below, and reference its key wherever it is used (hero, services, gallery).
 */
import type { ImageMetadata } from 'astro';
import patio from '../assets/photos/01-1000201888.jpg';
import glassShower from '../assets/photos/crops/03-glass-shower.jpg';
import soakingTub from '../assets/photos/05-1000201884.jpg';
import showerTub from '../assets/photos/06-1000201883.jpg';
import stairs from '../assets/photos/07-1000201882.jpg';
import kitchenIsland from '../assets/photos/crops/08-kitchen-island.jpg';
import office from '../assets/photos/09-1000201880.jpg';
import emptyRoom from '../assets/photos/10-1000201879.jpg';

export interface Photo {
  src: ImageMetadata;
  alt: string;
  /** CSS object-position used for responsive crops */
  position?: string;
}

export const photos = {
  kitchenIsland: {
    src: kitchenIsland,
    alt: 'A spotless quartz kitchen island with a vase of fresh pink and red flowers',
    position: '40% 45%',
  },
  showerTub: {
    src: showerTub,
    alt: 'A bright bathroom with a gleaming glass shower enclosure and a freestanding white tub',
    position: '50% 55%',
  },
  emptyRoom: {
    src: emptyRoom,
    alt: 'An empty, freshly cleaned room with hardwood floors, a globe chandelier and soft daylight',
    position: '50% 60%',
  },
  office: {
    src: office,
    alt: 'A tidy office meeting room with a long table, black chairs and clean wood-look floors',
    position: '50% 55%',
  },
  soakingTub: {
    src: soakingTub,
    alt: 'A freestanding white soaking tub against clean marble-look tile',
    position: '45% 55%',
  },
  glassShower: {
    src: glassShower,
    alt: 'A walk-in glass shower with polished chrome fixtures and a clean white base',
    position: '50% 45%',
  },
  stairs: {
    src: stairs,
    alt: 'A clean staircase with wood-look treads and bright white walls',
    position: '50% 55%',
  },
  patio: {
    src: patio,
    alt: 'A tidy covered patio with a dining table and cushioned chairs beside large windows',
    position: '68% 62%',
  },
} satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;

/** Hero rotation (first image loads eagerly). */
export const heroSlides: PhotoKey[] = ['kitchenIsland', 'showerTub', 'emptyRoom'];

/**
 * Optional short, muted hero video. Place the file in /public/media and set
 * e.g. { src: '/media/hero.mp4', poster: 'kitchenIsland' } to replace the slideshow.
 */
export const heroVideo: { src: string; poster: PhotoKey } | null = null;

/**
 * Optional portrait of Cindy for the "Meet Cindy" section. Only add a
 * confirmed photograph of Cindy, used with her permission. Import it above
 * and set it here, e.g. { src: cindyPortrait, alt: 'Cindy Albornoz…' }.
 */
export const cindyPortrait: Photo | null = null;

/**
 * Curated gallery, in display order. Every entry is a different photograph.
 */
export const gallery: { key: PhotoKey; caption: string }[] = [
  { key: 'kitchenIsland', caption: 'A fresh, welcoming kitchen' },
  { key: 'soakingTub', caption: 'Bathroom details' },
  { key: 'showerTub', caption: 'Glass and chrome that shine' },
  { key: 'emptyRoom', caption: 'Move-ready rooms' },
  { key: 'office', caption: 'Workspaces kept tidy' },
  { key: 'glassShower', caption: 'Showers, top to bottom' },
  { key: 'stairs', caption: 'Floors and stairways' },
  { key: 'patio', caption: 'Finishing touches, inside and out' },
];
