/**
 * Real Bright House photographs. Originals live in src/assets/photos and are
 * never modified; Astro generates optimized AVIF/WebP versions at build time.
 * Privacy-safe crops (photos 03 and 08) are generated by scripts/make-crops.mjs.
 *
 * To add or swap a photo: drop the file into src/assets/photos, import it
 * below, and reference its key wherever it is used (hero, services, gallery).
 */
import type { ImageMetadata } from 'astro';
import patio from '../assets/photos/01-1000201888.jpg';
import glassShower from '../assets/photos/crops/03-glass-shower.jpg';
import soakingTub from '../assets/photos/05-1000201884.jpg';
import showerTub from '../assets/photos/06-1000201883.jpg';
import stairs from '../assets/photos/07-1000201882.jpg';
import kitchenIsland from '../assets/photos/crops/08-kitchen-island.jpg';
import office from '../assets/photos/09-1000201880.jpg';
import emptyRoom from '../assets/photos/10-1000201879.jpg';
import regularService from '../assets/services/regular-cleaning.png';
import deepService from '../assets/services/deep-cleaning.png';
import moveService from '../assets/services/move-in-move-out.png';
import commercialService from '../assets/services/commercial-cleaning.png';
import airbnbService from '../assets/services/airbnb-turnover.png';
import cindy from '../assets/photos/cindy-bright-house-shirt-v2.webp';

export interface Photo {
  src: ImageMetadata;
  alt: string;
  /** CSS object-position used for responsive crops */
  position?: string;
}

export const photos = {
  kitchenIsland: {
    src: kitchenIsland,
    alt: 'A spotless quartz kitchen island with a vase of fresh pink and red flowers',
    position: '40% 45%',
  },
  showerTub: {
    src: showerTub,
    alt: 'A bright bathroom with a gleaming glass shower enclosure and a freestanding white tub',
    position: '50% 55%',
  },
  emptyRoom: {
    src: emptyRoom,
    alt: 'An empty, freshly cleaned room with hardwood floors, a globe chandelier and soft daylight',
    position: '50% 60%',
  },
  office: {
    src: office,
    alt: 'A tidy office meeting room with a long table, black chairs and clean wood-look floors',
    position: '50% 55%',
  },
  soakingTub: {
    src: soakingTub,
    alt: 'A freestanding white soaking tub against clean marble-look tile',
    position: '45% 55%',
  },
  glassShower: {
    src: glassShower,
    alt: 'A walk-in glass shower with polished chrome fixtures and a clean white base',
    position: '50% 45%',
  },
  stairs: {
    src: stairs,
    alt: 'A clean staircase with wood-look treads and bright white walls',
    position: '50% 55%',
  },
  patio: {
    src: patio,
    alt: 'A tidy covered patio with a dining table and cushioned chairs beside large windows',
    position: '68% 62%',
  },
} satisfies Record<string, Photo>;

export type PhotoKey = keyof typeof photos;

/**
 * Cindy's portrait for the "Meet Cindy" section (3:4, confirmed photo of Cindy).
 * Not part of the "Real Work" gallery.
 */
export const cindyPortrait: Photo | null = {
  src: cindy,
  alt: 'Cindy Albornoz, founder of Bright House Cleaning Services',
  position: '50% 0%',
};

/**
 * Curated gallery, in display order. Every entry is a different photograph.
 */
export const gallery: { key: PhotoKey; caption: string }[] = [
  { key: 'kitchenIsland', caption: 'A fresh, welcoming kitchen' },
  { key: 'soakingTub', caption: 'Bathroom details' },
  { key: 'showerTub', caption: 'Glass and chrome that shine' },
  { key: 'emptyRoom', caption: 'Move-ready rooms' },
  { key: 'office', caption: 'Workspaces kept tidy' },
  { key: 'glassShower', caption: 'Showers, top to bottom' },
  { key: 'stairs', caption: 'Floors and stairways' },
  { key: 'patio', caption: 'Finishing touches, inside and out' },
];

/**
 * Service-card photography (one image per service). These are illustrative
 * brand images, not client work: never add them to the "Real Work" gallery or
 * use them as Cindy's portrait. `position` is the object-position used for the
 * 16:9 card crop, tuned per image to keep the cleaner and the task in frame.
 */

export const servicePhotos: Record<'regular' | 'deep' | 'move' | 'commercial' | 'airbnb', Photo> = {
  regular: { src: regularService, alt: 'Bright House cleaner caring for a bright living room', position: '50% 28%' },
  deep: { src: deepService, alt: 'Bright House cleaner detailing a glass shower', position: '50% 18%' },
  move: { src: moveService, alt: 'Bright House cleaner vacuuming an empty condo', position: '50% 30%' },
  commercial: { src: commercialService, alt: 'Bright House cleaner sanitizing an office meeting room', position: '50% 32%' },
  airbnb: { src: airbnbService, alt: 'Bright House cleaner preparing a guest bedroom', position: '50% 22%' },
};
